### ISSUE TITLE
Boilerplating

### ISSUE THREAD

**Issue by haydenhughes** [loser-lagoon-studios/STEM-Game#1]
Create a basic Unity3D project as a boilerplate. The game can then be built on top of the boiler plate to via pull requests. 

TODO:

- [x] Create a blank Unity3D 2D project 
- [x] with appropriate settings.
- [x] Setup a file structure for assets.
- [x] Add TextMesh Pro to the project

**Comment by Nylme** [comment]
what do you mean "with appropriate settings."
I've made the boilerplate so i just need to know what settings are appropriate.
thanks -emlyn

**Comment by haydenhughes** [comment]
See pull #4
